# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 4) do

  create_table "profiles", :force => true do |t|
    t.column "jid",        :string
    t.column "fullname",   :string
    t.column "url",        :string
    t.column "tweetcount", :integer, :default => 0
  end

  create_table "tweets", :force => true do |t|
    t.column "name",       :string
    t.column "content",    :string
    t.column "created_on", :datetime
    t.column "profile_id", :integer
  end

end
